version: '3.8'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER:     "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:       "${POSTGRES_DB}"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      # Conexión a la DB (host db, no localhost)
      SPRING_DATASOURCE_URL:      jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Dialecto y auto‐DDL
      SPRING_JPA_DATABASE_PLATFORM:   org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO:  update
      # JWT
      JWT_SECRET:        ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    depends_on:
      - db

volumes:
  db-data:
